# Generated by Django 2.2.5 on 2019-10-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licno', models.IntegerField()),
                ('ild', models.DateField()),
                ('fno', models.CharField(max_length=250)),
                ('iec', models.IntegerField()),
                ('pname', models.CharField(max_length=300)),
                ('lic', models.CharField(max_length=300)),
                ('fob', models.FloatField()),
                ('cif', models.FloatField()),
            ],
        ),
    ]
